#!/bin/bash

if [ -z "$SSL_DOMAIN" ]; then

    echo "You need the SSL_DOMAIN variables"

else

    if [ -f /etc/letsencrypt/live/$SSL_DOMAIN/fullchain.pem ]; then

        /usr/bin/certbot renew --dry-run
        /usr/bin/supervisorctl restart nginx

    else

        echo "Certificate can not be found"

    fi
fi
